### PR TITLE
port Rholang linker using scala.js

### PR DESCRIPTION
**Pull request by dckc**
it compiles, but the file IO is stubbed out

not ready to merge. just FYI

### CODE REVIEW

**Comment by tschoffelen** [comment]
Looks exciting! 

Can you explain to me what the exact goal is of porting the Scala linker to JS? Is it to add the ‘extended Rholang’ support that was being talked about in Discord?

**Comment by dckc** [comment]
Yes

**Comment by tschoffelen** [comment]
Great! I wonder if it is easier to just port that over manually, rather than using a Scala to JS converter, since the JS code it creates seems to be a little long/complex (22k+ LOC) compared to the original (<300 LOC).

Then again, you have probably already been thinking about this, so I should probably just let you work on this instead of commenting before it is finished :)

**Comment by dckc** [comment]
Porting by hand is quite likely straightforward. This is as much me testing how mature scala.js is as anything. Ultimately, I doubt taking on a scala.js dependency is cost-effective. I don't know if you'll ever want to merge this. But I figured this is as good as any place to put the bits on the net while I'm working on them.

**Comment by dckc** [comment]
Well, it seems to work now:

```
$ node target/scala-2.12/rholang-linker-opt.js .../packages/ MakeBrandPairTest.rho
Wrote MakeBrandPairTest.rho.linked
```

cc @deannald

**Comment by dckc** [comment]
@tschoffelen ping? I'm interested in your thoughts on this, now that it seems to work.

**Comment by tschoffelen** [comment]
Unfortunately haven’t really found the time to look into this yet, as my primary focus is finishing #9 this week. Will look at incorporating this PR straight after that!

**Comment by tschoffelen** [comment]
Finally had a chance to look at this. Pretty impressive that it is so (relatively) straightforward to compile Scala into JS.

I wonder though how you see this working on rchain.cloud, since we don't support multiple files right now, and that's the only real use case I see for even supporting the `import`/`export` keywords, with the only exception being supporting every single feature of the language, although it isn't really part of the language itself at the moment.

What perhaps might be cool though for future development is to publish this as a NPM package named `rholang-linker`, allowing other devs to use this code, and without having to add the generated scala.js target code into this repo.

**Comment by tschoffelen** [comment]
Closing this for now as it isn't relevant to the current development of RChain.cloud. I still think it might be interested to create a separate repo/NPM package around this though!

**Pull request closed without merging**
