### PR TITLE
Added Presentation Mode and Editor Font Size adjustment buttons

### PR DESCRIPTION
**Pull request by aostrun**
Presentation Mode is activated with key bind "Ctrl + Alt + p" as suggested.
Entering Presentation Mode, the font size is automatically incremented by 10px, this can be lowered or even turned to the relative increment if this doesn't suffice.
Editor Font Size adjustment buttons are added to the header.

### CODE REVIEW

**Comment by aostrun** [comment]
Also added a horizontal draggable line that allows dynamic change of editor/console width.

**Comment by tschoffelen** [comment]
Great work!

Two little suggestions about presentation mode:

- I think the 'Your code' header can be hidden as well
- Could you center the code editor horizontally in the middle of the screen (max width 980px or something similar)

**Comment by aostrun** [comment]
Thank you!
The label 'Your code' is now removed from the presentation mode and the editor/code is now centered on desktops (screens larger than 980px) in the presentation mode.

**Comment by tschoffelen** [comment]
Awesome!

Will deploy this later this week.

**Pull request merged**
